#!/bin/bash
# Now that I have had to do this more than once
# because the league / TFT client just stops working
# I'm just making a script so I no longer need to google it
rm -rf /Users/Shared/Riot\ Games/
rm -rf /Library/Application\ Support/Riot\ Games/


